"""added bio and quote to user

Revision ID: 50f9284f5b36
Revises: b5512902260f
Create Date: 2022-01-16 10:24:12.802725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50f9284f5b36'
down_revision = 'b5512902260f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_quote', sa.Text(length=500), nullable=True))
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('users', 'about_author')
    op.drop_column('users', 'favorite_quote')
    # ### end Alembic commands ###
